import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    HRFlowable, ListFlowable, ListItem,
    Table, TableStyle
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import html

def _escape(text: str) -> str:
    if not isinstance(text, str):
        return str(text)
    return html.escape(text)


def generate_summary_pdf(summary: dict) -> bytes:
    """Generate formatted PDF from single document summary."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=0.8 * inch, leftMargin=0.8 * inch,
        topMargin=0.8 * inch, bottomMargin=0.8 * inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=22, textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6, alignment=TA_CENTER, fontName="Helvetica-Bold",
    )
    section_heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"],
        fontSize=13, textColor=colors.HexColor("#16213e"),
        spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontSize=10.5, textColor=colors.HexColor("#333333"),
        spaceAfter=6, leading=16, fontName="Helvetica",
    )
    highlight_style = ParagraphStyle(
        "Highlight", parent=styles["Normal"],
        fontSize=10.5, textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6, leading=16, leftIndent=12,
        fontName="Helvetica-Oblique",
    )
    keyword_style = ParagraphStyle(
        "Keyword", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#4a90d9"),
        fontName="Helvetica-Bold",
    )
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#999999"),
        alignment=TA_CENTER,
    )

    story = []

    # Title
    safe_title = _escape(summary.get("title", "Document Summary"))
    story.append(Paragraph(safe_title, title_style))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=2,
                            color=colors.HexColor("#4a90d9"), spaceAfter=12))

    # Summary
    story.append(Paragraph("Summary", section_heading_style))
    safe_summary = _escape(summary.get("summary", ""))
    story.append(Paragraph(safe_summary, body_style))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#cccccc"), spaceAfter=6))

    # Key Points
    story.append(Paragraph("Key Points", section_heading_style))
    bullets = summary.get("bullets", [])
    bullet_items = [
        ListItem(Paragraph(_escape(bullet), body_style),
                 bulletColor=colors.HexColor("#4a90d9"), leftIndent=20)
        for bullet in bullets
    ]
    story.append(ListFlowable(bullet_items, bulletType="bullet", start="•"))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#cccccc"), spaceAfter=6))

    # Highlights
    story.append(Paragraph("Highlights", section_heading_style))
    for highlight in summary.get("highlights", []):
        story.append(Paragraph(f'"{_escape(highlight)}"', highlight_style))
        story.append(Spacer(1, 4))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#cccccc"), spaceAfter=6))

    # Keywords
    story.append(Paragraph("Keywords", section_heading_style))
    keywords_text = "   |   ".join([f"#{_escape(kw)}" for kw in summary.get("keywords", [])])
    story.append(Paragraph(keywords_text, keyword_style))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1,
                            color=colors.HexColor("#4a90d9"), spaceAfter=6))
    story.append(Paragraph("Generated by Document Summarizer AI", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def generate_table_pdf(summaries: list[dict]) -> bytes:
    """Generate formatted PDF table from multiple document summaries."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=0.5 * inch, leftMargin=0.5 * inch,
        topMargin=0.8 * inch, bottomMargin=0.8 * inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TableTitle", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6, alignment=TA_CENTER, fontName="Helvetica-Bold",
    )
    cell_style = ParagraphStyle(
        "CellStyle", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#333333"),
        leading=12, fontName="Helvetica",
    )
    header_style = ParagraphStyle(
        "HeaderStyle", parent=styles["Normal"],
        fontSize=9, textColor=colors.white,
        fontName="Helvetica-Bold", alignment=TA_CENTER,
    )
    info_style = ParagraphStyle(
        "Info", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#666666"),
        spaceAfter=12, fontName="Helvetica",
    )
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#999999"),
        alignment=TA_CENTER,
    )

    story = []

    # Title
    story.append(Paragraph("Document Summaries Report", title_style))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=2,
                            color=colors.HexColor("#4a90d9"), spaceAfter=12))
    story.append(Paragraph(f"Total Documents Analyzed: {len(summaries)}", info_style))

    # Table header
    header_row = [
        Paragraph("Document Name", header_style),
        Paragraph("Summary", header_style),
        Paragraph("Keywords", header_style),
        Paragraph("Highlights", header_style),
    ]
    table_data = [header_row]

    # Data rows
    for summary_item in summaries:
        keywords = "\n".join(["#" + _escape(kw) for kw in summary_item.get("keywords", [])])
        highlight_list = summary_item.get("highlights", [])
        highlights = "\n\n".join([
            str(i+1) + ". " + _escape(h)
            for i, h in enumerate(highlight_list)
        ])
        row = [
            Paragraph(_escape(summary_item.get("name", "Unknown")), cell_style),
            Paragraph(_escape(summary_item.get("summary", "")), cell_style),
            Paragraph(keywords, cell_style),
            Paragraph(highlights, cell_style),
        ]
        table_data.append(row)

    # Page width in A4 is 595.27 points (8.27 in). Printable width is 595.27 - 2 * 36 = 523.27 points
    # Col widths: 1.5 inch, 2.5 inch, 1.25 inch, 2.0 inch -> total 7.25 inches (522 points)
    col_widths = [1.5 * inch, 2.5 * inch, 1.25 * inch, 2.0 * inch]
    
    t = Table(table_data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
        ('TOPPADDING', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    
    story.append(t)
    
    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1,
                            color=colors.HexColor("#4a90d9"), spaceAfter=6))
    story.append(Paragraph("Generated by Document Summarizer AI", footer_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer.read()